import { createPortal } from 'react-dom'
import type { ItemSplit, Person, ReceiptItem, ScannedReceipt, Settlement } from '@/types'
import { getItemShares, detectDiscountType, calculatePersonTotals } from '@/utils/balanceCalculator'

function round(n: number): number {
  return Math.round(n * 100) / 100
}

interface Props {
  receipt: ScannedReceipt
  items: ReceiptItem[]
  splits: ItemSplit[]
  people: Person[]
  settlements: Settlement[]
}

export default function PrintContent({ receipt, items, splits, people, settlements }: Props) {
  const date = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })
  const rawTotals = calculatePersonTotals(items, splits, people, null, receipt.store)
  const hr = <div style={{ borderTop: '1px solid #ccc', margin: '12px 0' }} />

  // Per-person discount contributions for the PDF
  const discountSharesById: Record<string, number> = {}
  people.forEach(p => { discountSharesById[p.id] = 0 })
  items.forEach((item, idx) => {
    if (item.type !== 'discount') return
    const shares = getItemShares(item, idx, items, splits, people, receipt.store)
    Object.entries(shares).forEach(([id, v]) => {
      discountSharesById[id] = round(discountSharesById[id] + v)
    })
  })
  const hasDiscounts = items.some(i => i.type === 'discount')

  const content = (
    <div id="print-content">
      {/* Header */}
      <div style={{ borderBottom: '2px solid #000', paddingBottom: 8, marginBottom: 12 }}>
        <p style={{ fontWeight: 700, fontSize: 16, margin: 0 }}>SPLITHAUS — Receipt Summary</p>
        <p style={{ color: '#666', margin: '2px 0 0' }}>{receipt.store} · {date}</p>
      </div>

      {/* Items */}
      <p style={{ fontWeight: 600, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#888', margin: '0 0 8px' }}>
        Items &amp; How They Were Split
      </p>
      {items.map((item, idx) => {
        const shares = getItemShares(item, idx, items, splits, people, receipt.store)
        const assignments = people
          .filter(p => Math.abs(shares[p.id] ?? 0) >= 0.01)
          .map(p => `${p.name}: ${shares[p.id] < 0 ? '-' : ''}$${Math.abs(shares[p.id]).toFixed(2)}`)
          .join(' · ')
        const discType = item.type === 'discount' ? detectDiscountType(item.name, receipt.store) : null
        const discNote = discType === 'ww_brand' ? ' (WW items only)' : discType === 'team' ? ' (proportional)' : ''
        return (
          <div key={idx} style={{ marginBottom: 6, pageBreakInside: 'avoid' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>{item.name}</span>
              <span style={{ fontFamily: 'monospace' }}>{item.price < 0 ? '-' : ''}${Math.abs(item.price).toFixed(2)}</span>
            </div>
            {assignments && (
              <div style={{ color: '#555', fontSize: 12, paddingLeft: 12 }}>→ {assignments}{discNote}</div>
            )}
          </div>
        )
      })}

      {hr}

      {/* Per-person totals */}
      <p style={{ fontWeight: 600, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#888', margin: '0 0 6px' }}>
        Each Person's Share
      </p>
      {people.map(p => {
        const net = rawTotals[p.id] ?? 0
        const discShare = discountSharesById[p.id] ?? 0
        const itemsShare = round(net - discShare)
        return (
          <div key={p.id} style={{ marginBottom: hasDiscounts ? 6 : 3, pageBreakInside: 'avoid' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ fontWeight: 500 }}>{p.name}</span>
              <span style={{ fontFamily: 'monospace' }}>${net.toFixed(2)}</span>
            </div>
            {hasDiscounts && discShare < 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, color: '#666', paddingLeft: 12 }}>
                <span>Items: ${itemsShare.toFixed(2)}</span>
                <span style={{ color: '#C84B31' }}>Discount: -${Math.abs(discShare).toFixed(2)}</span>
              </div>
            )}
          </div>
        )
      })}

      {hr}

      {/* Settlements */}
      <p style={{ fontWeight: 600, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#888', margin: '0 0 6px' }}>
        Settlements
      </p>
      {settlements.length === 0
        ? <p style={{ color: '#666' }}>No settlements needed — everyone's even!</p>
        : settlements.map((s, i) => (
          <p key={i} style={{ margin: '3px 0' }}>{s.fromName} pays {s.toName} ${s.amount.toFixed(2)}</p>
        ))
      }

      {hr}

      {/* Footer */}
      <div style={{ color: '#888', fontSize: 11 }}>
        <p style={{ margin: 0 }}>Total: ${receipt.total.toFixed(2)} · GST: ${receipt.gst.toFixed(2)}</p>
        <p style={{ margin: '2px 0 0' }}>Generated by SplitHaus · splithaus.vercel.app</p>
      </div>
    </div>
  )

  return createPortal(content, document.body)
}
