import type { ItemSplit, Person, ReceiptItem, ScannedReceipt, Settlement } from '@/types'
import { getItemShares } from '@/utils/balanceCalculator'

interface Props {
  receipt: ScannedReceipt
  items: ReceiptItem[]
  splits: ItemSplit[]
  people: Person[]
  settlements: Settlement[]
}

export default function PrintContent({ receipt, items, splits, people, settlements }: Props) {
  const date = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })

  return (
    <div id="print-content" className="hidden p-8 font-sans text-ink">
      <div className="border-b-2 border-ink pb-2 mb-4">
        <p className="text-xs font-mono font-semibold uppercase tracking-wider text-ink-2">SPLITHAUS — Receipt Summary</p>
        <p className="mt-0.5 text-sm text-ink-2">{receipt.store} · {date}</p>
      </div>

      <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-ink-2">Items &amp; How They Were Split</p>

      <div className="space-y-2 mb-4">
        {items.map((item, idx) => {
          const shares = getItemShares(item, idx, items, splits, people, receipt.store)
          const assignments = people
            .filter(p => Math.abs(shares[p.id] ?? 0) >= 0.01)
            .map(p => `${p.name}: ${shares[p.id] < 0 ? '-' : ''}$${Math.abs(shares[p.id]).toFixed(2)}`)
            .join(' · ')
          return (
            <div key={idx}>
              <div className="flex justify-between">
                <span className="text-sm">{item.name}</span>
                <span className="font-mono text-sm">{item.price < 0 ? '-' : ''}${Math.abs(item.price).toFixed(2)}</span>
              </div>
              {assignments && (
                <p className="text-xs text-ink-2 ml-3">→ {assignments}</p>
              )}
            </div>
          )
        })}
      </div>

      <div className="border-t border-ink pt-3 mb-4">
        <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-ink-2">Settlements</p>
        {settlements.length === 0
          ? <p className="text-sm text-ink-2">No settlements needed — everyone's even!</p>
          : settlements.map((s, i) => (
            <p key={i} className="text-sm">{s.fromName} pays {s.toName} ${s.amount.toFixed(2)}</p>
          ))
        }
      </div>

      <div className="border-t border-rule pt-3 text-xs text-ink-2">
        <p>Total: ${receipt.total.toFixed(2)} · GST: ${receipt.gst.toFixed(2)}</p>
        <p>Generated by SplitHaus · splithaus.vercel.app</p>
      </div>
    </div>
  )
}
